export type ItemCategory =
  | 'top'
  | 'back'
  | 'shoulder'
  | 'neck'
  | 'front'
  | 'waist'
  | 'gear'
  | 'shirt'
  | 'tshirt'
  | 'pants'
  | 'face';

export interface CatalogItem {
  id: string;
  name: string;
  category: ItemCategory;
  price: number; // in Bloxies (0 = free)
  description: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary' | 'mythic';
  colorHex?: string;
  glow?: boolean;
}

export const CATALOG_ITEMS: CatalogItem[] = [
  // --- TOP / DOMINUS & HATS ---
  {
    id: 'dom_vampirus',
    name: 'Vampirus Devilius Dominus',
    category: 'top',
    price: 800000,
    description: 'The most mythical and expensive crown in BloxMania. Features abyssal crimson horns, shadowy hood, and glowing dark aura.',
    rarity: 'mythic',
    colorHex: '#800020',
    glow: true,
  },
  {
    id: 'dom_infernus',
    name: 'Dominus Infernus',
    category: 'top',
    price: 500000,
    description: 'Forged in the molten core of Doomspire. Radiant burning embers and black obsidian horns.',
    rarity: 'mythic',
    colorHex: '#d63031',
    glow: true,
  },
  {
    id: 'dom_frigidus',
    name: 'Dominus Frigidus',
    category: 'top',
    price: 400000,
    description: 'Carved from ancient glacial ice. Frostbite aura and freezing azure horns.',
    rarity: 'mythic',
    colorHex: '#00cec9',
    glow: true,
  },
  {
    id: 'sparkle_fedora',
    name: 'Sparkle Time Fedora',
    category: 'top',
    price: 120000,
    description: 'Legendary midnight fedora laced with sparkling purple jewels.',
    rarity: 'legendary',
    colorHex: '#6c5ce7',
    glow: true,
  },
  {
    id: 'valk_helm',
    name: 'Valkyrie Helm',
    category: 'top',
    price: 90000,
    description: 'Ancient warrior helm with gleaming golden wing plumes.',
    rarity: 'legendary',
    colorHex: '#fdcb6e',
  },
  {
    id: 'clockwork_shades',
    name: 'Clockwork Shades',
    category: 'top',
    price: 75000,
    description: 'Timeless retro sunglasses with gold gear trim.',
    rarity: 'legendary',
    colorHex: '#2d3436',
  },
  {
    id: 'golden_crown',
    name: 'Royal Golden Crown',
    category: 'top',
    price: 5000,
    description: 'Pure 24-karat gold crown with ruby crests.',
    rarity: 'epic',
    colorHex: '#f1c40f',
  },
  {
    id: 'top_wizard',
    name: 'Classic Wizard Hat',
    category: 'top',
    price: 150,
    description: 'Pointy blue wizard cap dotted with stars.',
    rarity: 'rare',
    colorHex: '#0984e3',
  },
  {
    id: 'top_ninja',
    name: 'Ninja Headband',
    category: 'top',
    price: 50,
    description: 'Black stealth headband with silver crest.',
    rarity: 'common',
    colorHex: '#2d3436',
  },
  {
    id: 'free_cap',
    name: 'Classic Blox Baseball Cap',
    category: 'top',
    price: 0,
    description: 'Traditional red and blue starter cap. Always free!',
    rarity: 'common',
    colorHex: '#d63031',
  },

  // --- BACK ACCESSORIES ---
  {
    id: 'back_devil_wings',
    name: 'Crimson Demon Wings',
    category: 'back',
    price: 2500,
    description: 'Massive bat-like crimson demon wings that spread wide behind you.',
    rarity: 'epic',
    colorHex: '#c0392b',
    glow: true,
  },
  {
    id: 'back_angel_wings',
    name: 'Divine Angel Wings',
    category: 'back',
    price: 3000,
    description: 'Pure feathered white wings radiating warm golden light.',
    rarity: 'epic',
    colorHex: '#ffffff',
    glow: true,
  },
  {
    id: 'back_katana',
    name: 'Dual Golden Katanas',
    category: 'back',
    price: 800,
    description: 'Crossed dual samurai swords sheathed on your back.',
    rarity: 'rare',
    colorHex: '#f39c12',
  },
  {
    id: 'back_jetpack',
    name: 'Retro Rocket Jetpack',
    category: 'back',
    price: 350,
    description: 'Twin-thruster rocket pack with retro dials.',
    rarity: 'rare',
    colorHex: '#e17055',
  },
  {
    id: 'back_cape',
    name: 'Heroic Red Cape',
    category: 'back',
    price: 100,
    description: 'Flowing hero cape that billows in the wind.',
    rarity: 'common',
    colorHex: '#e74c3c',
  },

  // --- SHOULDER ACCESSORIES ---
  {
    id: 'shld_dragon',
    name: 'Golden Shoulder Dragon',
    category: 'shoulder',
    price: 1200,
    description: 'A miniature golden dragon perched proudly on your left shoulder.',
    rarity: 'epic',
    colorHex: '#f1c40f',
    glow: true,
  },
  {
    id: 'shld_parrot',
    name: 'Pirate Parrot',
    category: 'shoulder',
    price: 200,
    description: 'Squawking colorful tropical parrot.',
    rarity: 'rare',
    colorHex: '#00b894',
  },
  {
    id: 'shld_pet_noob',
    name: 'Mini Shoulder Noob',
    category: 'shoulder',
    price: 75,
    description: 'A tiny cute R6 Noob buddy resting on your shoulder.',
    rarity: 'common',
    colorHex: '#F5CD30',
  },

  // --- NECK ACCESSORIES ---
  {
    id: 'neck_gold_chain',
    name: 'Heavy Bling Gold Chain',
    category: 'neck',
    price: 400,
    description: 'Thick chunky Cuban link chain with dollar sign medallion.',
    rarity: 'rare',
    colorHex: '#f39c12',
  },
  {
    id: 'neck_scarf',
    name: 'Cozy Winter Scarf',
    category: 'neck',
    price: 60,
    description: 'Warm red and white knitted scarf wrapped around your neck.',
    rarity: 'common',
    colorHex: '#d63031',
  },
  {
    id: 'neck_royal_tie',
    name: 'Diamond Bowtie',
    category: 'neck',
    price: 120,
    description: 'Classy formal bowtie with diamond pin.',
    rarity: 'rare',
    colorHex: '#2c3e50',
  },

  // --- FRONT ACCESSORIES ---
  {
    id: 'front_badge',
    name: 'BloxMania Star Badge',
    category: 'front',
    price: 80,
    description: 'Golden sheriff star badge pinned to your chest.',
    rarity: 'common',
    colorHex: '#f1c40f',
  },
  {
    id: 'front_vest',
    name: 'Tactical Kevlar Vest',
    category: 'front',
    price: 220,
    description: 'Heavy duty tactical vest with pouches.',
    rarity: 'rare',
    colorHex: '#2d3436',
  },

  // --- WAIST ACCESSORIES ---
  {
    id: 'waist_sword',
    name: 'Side Rapier Sword',
    category: 'waist',
    price: 300,
    description: 'Ornate fencing rapier sheathed at your hip.',
    rarity: 'rare',
    colorHex: '#bdc3c7',
  },
  {
    id: 'waist_tail',
    name: 'Fluffy Fox Tail',
    category: 'waist',
    price: 150,
    description: 'Cute orange fluffy tail swaying with your steps.',
    rarity: 'common',
    colorHex: '#e67e22',
  },
  {
    id: 'waist_belt',
    name: 'Utility Belt',
    category: 'waist',
    price: 90,
    description: 'Black leather belt with brass buckle and compartments.',
    rarity: 'common',
    colorHex: '#2c3e50',
  },

  // --- GEAR (HELD ITEMS) ---
  {
    id: 'gear_classic_trowel',
    name: 'Classic Builder Trowel',
    category: 'gear',
    price: 0,
    description: 'The legendary trowel tool that builds brick barriers! Always free.',
    rarity: 'common',
    colorHex: '#95a5a6',
  },
  {
    id: 'gear_gravity_coil',
    name: 'Gravity Coil',
    category: 'gear',
    price: 1500,
    description: 'Glowing blue coil that reduces gravity and lets you jump twice as high!',
    rarity: 'epic',
    colorHex: '#0984e3',
    glow: true,
  },
  {
    id: 'gear_speed_coil',
    name: 'Speed Coil',
    category: 'gear',
    price: 1200,
    description: 'Glowing red spiral coil that doubles your movement speed!',
    rarity: 'epic',
    colorHex: '#d63031',
    glow: true,
  },
  {
    id: 'gear_slingshot',
    name: 'Classic Slingshot',
    category: 'gear',
    price: 250,
    description: 'Wooden Y-frame slingshot with red rubber band.',
    rarity: 'rare',
    colorHex: '#a06e3b',
  },
  {
    id: 'gear_golden_trophy',
    name: '1st Place Champion Trophy',
    category: 'gear',
    price: 10000,
    description: 'Gleaming golden victory cup held high in your hand.',
    rarity: 'legendary',
    colorHex: '#f1c40f',
  },

  // --- SHIRTS ---
  {
    id: 'free_shirt',
    name: 'Vintage Blox Blue Hoodie',
    category: 'shirt',
    price: 0,
    description: 'Classic cobalt blue hoodie with white drawstring. Always free!',
    rarity: 'common',
    colorHex: '#0984e3',
  },
  {
    id: 'shirt_tuxedo',
    name: 'Secret Agent Tuxedo',
    category: 'shirt',
    price: 80,
    description: 'Sharp black tuxedo with crisp white collared shirt.',
    rarity: 'rare',
    colorHex: '#1e272e',
  },
  {
    id: 'shirt_cyber',
    name: 'Cyberpunk Neon Armor',
    category: 'shirt',
    price: 150,
    description: 'Futuristic combat shirt glowing with cyan circuits.',
    rarity: 'epic',
    colorHex: '#00cec9',
    glow: true,
  },
  {
    id: 'shirt_superhero',
    name: 'Red Flash Superhero Suit',
    category: 'shirt',
    price: 120,
    description: 'Spandex hero top with bold lightning chest crest.',
    rarity: 'rare',
    colorHex: '#e84118',
  },
  {
    id: 'shirt_stripes',
    name: 'Retro Striped Tee',
    category: 'shirt',
    price: 40,
    description: 'Casual horizontal black and white striped tee.',
    rarity: 'common',
    colorHex: '#636e72',
  },

  // --- T-SHIRTS (TORSO DECALS) ---
  {
    id: 'free_tshirt_smile',
    name: 'Classic Happy Smiley',
    category: 'tshirt',
    price: 0,
    description: 'The iconic retro yellow happy face printed on your chest. Free!',
    rarity: 'common',
    colorHex: '#f1c40f',
  },
  {
    id: 'tshirt_bloxmania',
    name: 'BloxMania Official Logo',
    category: 'tshirt',
    price: 30,
    description: 'Official BloxMania gaming portal emblem.',
    rarity: 'common',
    colorHex: '#e74c3c',
  },
  {
    id: 'tshirt_doge',
    name: 'Much Wow Doge Decal',
    category: 'tshirt',
    price: 75,
    description: 'Very cool. Much swag. Wow.',
    rarity: 'rare',
    colorHex: '#f39c12',
  },
  {
    id: 'tshirt_pizza',
    name: 'Noobs Fresh Pizza',
    category: 'tshirt',
    price: 45,
    description: 'Hot melted brick pizza slice graphic.',
    rarity: 'common',
    colorHex: '#e67e22',
  },
  {
    id: 'tshirt_fire',
    name: 'Flaming Skull Decal',
    category: 'tshirt',
    price: 90,
    description: 'Radical flaming skull with sunglasses.',
    rarity: 'rare',
    colorHex: '#d63031',
  },

  // --- PANTS ---
  {
    id: 'free_pants',
    name: 'Classic Blue Jeans',
    category: 'pants',
    price: 0,
    description: 'Standard comfortable denim jeans. Always free!',
    rarity: 'common',
    colorHex: '#2980b9',
  },
  {
    id: 'pants_cargo',
    name: 'Black Tactical Cargo Pants',
    category: 'pants',
    price: 70,
    description: 'Rugged black utility trousers with side pockets.',
    rarity: 'rare',
    colorHex: '#2d3436',
  },
  {
    id: 'pants_gold',
    name: 'Pure Golden Trousers',
    category: 'pants',
    price: 5000,
    description: 'Woven from solid spun gold threads.',
    rarity: 'epic',
    colorHex: '#f1c40f',
  },
  {
    id: 'pants_camo',
    name: 'Desert Camo Slacks',
    category: 'pants',
    price: 60,
    description: 'Tactical desert camouflage pattern pants.',
    rarity: 'common',
    colorHex: '#a06e3b',
  },
];
